nelmio_cors:
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['Authorization', 'X-AUTH-USER', 'X-AUTH-TOKEN', 'Content-Type']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            max_age: 3600
